version: 2
updates:
  # Maintain dependencies for Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      # Check for updates to Go modules every weekday
      interval: "daily"
    groups:
      hashicorp: # Group all HashiCorp dependencies together
        patterns:
          - "github.com/hashicorp/*"
  - package-ecosystem: "gomod"
    directory: "/tools"
    schedule:
      interval: "daily"
    groups:
      hashicorp: # Group all HashiCorp dependencies together
        patterns:
          - "github.com/hashicorp/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"